---
project: web
dns_resolver: 192.168.1.1

#vm_os_type: centos-7.3
vm_distribution: centos
vm_release: 7.3

#for centos image disk size is working only default 6G and custom 10G
vm_image_size: 10G

vm_memory: 1024
vm_image_dir: /virt/sen-imgs
os_root_password: 123
vm_vnc_port: 63800
#each node will have its own port with increment 1 according to list

#network definition
networks:
  - name: mgmt
    config:
      - gateway: 192.168.102.1
        netmask: 255.255.255.0
  - name: prod
    config:
      - gateway: 192.168.103.1
        netmask: 255.255.255.0

first_ip_address: 10

vm_net_dir: /etc/sysconfig/network-scripts/
vm_net_model: e1000

#all other ip addresses will be with the step 1
#derived from network_gateway and first_ip_address

#nodes listing:
nodes:
  - manager
  - node1
  - node2
  - node3

dns_planned: False

additional_packages:
  - vim
  - ranger
  - git

proxy_env:
  http_proxy: "http://192.168.1.1:3128"
#  https_proxy: "https://192.168.1.1:3128"

ntp_config_server: 192.168.1.1
timezone: "Europe/Bratislava"

#ansible_python_interpreter: /usr/bin/python3
ansible_python_interpreter: /usr/bin/python
