---
#install k8

- name: prepare repository for k8
  template:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    owner: root
    group: root
    mode: 0644

- name: install kubelet kubeadm kubectl kubernetescni
  yum:
    name: "{{ item }}"
    update_cache: yes
    disable_gpg_check: yes
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
    - kubernetes-cni

- name: systemctl enable kubelet and start kubelet
  systemd:
    name: kubelet
    state: started
    enabled: yes
