---

- name: run own private docker registry
  docker_container:
    name: registry
    image: "{{ docker_registry }}"
    restart_policy: always
    #ip:hostPort:containerPort
    published_ports: 5000:5000
  tags: registry_run


#deploy the custom containers
- block:

  - name: delete the previous versions of images if exist
    docker_image:
      name: localhost:5000/{{item}}
      state: absent
      force: True
    with_items: "{{dockerfiles}}"
    tags: images_push

  - name: create directory for dockerfiles
    file:
      path: "/docker/{{item}}"
      state: directory
    with_items: "{{dockerfiles}}"
    tags: images_push

  - name: copy dockerfiles for containers needed
    synchronize:
      src: "docker/{{item}}"
      dest: /docker/
    with_items: "{{dockerfiles}}"
    tags: images_push

  - name: Build an image and push it to a private repo
    docker_image:
      path: /docker/{{item}}
      name: localhost:5000/{{item}}
      push: yes
    with_items: "{{dockerfiles}}"
    tags: images_push

  when: dockerfiles is defined
